model:
  name: 'MinkUNet18'
  in_feat_size: 1
  out_classes: 7
  drop_prob: 0.5

dataset:
  version: 'full'
  name: 'nuScenes'
  dataset_path: 'data/nuScenes-lidarseg/'
  split_path: null
  target_path: ''
  voxel_size: 0.05
  num_pts: 50000
  ignore_label: -1
  validate_target: false
  augment_data: false
  max_time_window: 1
  oracle_pts: 0
  mapping_path: '_resources/nuscenes.yaml'

pipeline:
  epochs: 1
  gpu: 0
  precision: 32
  loss: 'SoftDICELoss'
  ssl_loss: 'CosineSimilarity'
  eps: 0.25
  ssl_beta: 0.5
  segmentation_beta: 1.0
  seed: 1234
  save_dir: 'experiments/gipso/synth4dnusc/'
  source_model: 'pretrained_models/source/synth4dnusc/epoch=99-step=12499.ckpt'
  student_model: null
  topk_matches: -1
  random_time_window: false
  freeze_list: null
  topk_pseudo: null
  th_pseudo: 0.
  delayed_freeze_list: null
  delayed_freeze_frames: null
  is_double: true
  is_pseudo: true
  use_mcmc: true
  sub_epoch: 1
  num_mc_iterations: 5
  top_class: 0
  propagate: true
  top_p: 0.1
  propagation_size: 5
  metric: 'mcmc_cbst'
  use_matches: false
  propagation_method: 'geometric_features'

  dataloader:
    stream_batch_size: 1
    adaptation_batch_size: 1
    num_workers: 10

  optimizer:
    name: 'Adam'
    lr: 0.001
    scheduler: false

  scheduler:
    scheduler_name: 'ExponentialLR'

  trainer:
    save_checkpoint_every: 200
    clear_cache_int: 1
    num_sanity_val_steps: 0


  wandb:
    run_name: 'GIPSO-Synth2NUSCENES'
    project_name: 'amazing-project'
    entity_name: 'name'
    offline: false

